spring.main.banner-mode: off

server:
  port: 8080

logging:
  config: classpath:config/logback.xml
  level:
    springfox: DEBUG
    ru: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: false

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  url: jdbc:postgresql://localhost:5432/nailsme
  username: nailsme
  password: nailsme

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    javax:
      persistence:
        create-database-schemas: true
  hibernate.ddl-auto: update
  show-sql: false
  open-in-view: false

spring:
  application:
    name: nails-me-service
  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:20}

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true

bot:
  name: FinargotNailsMeBot
  token: 6036148459:AAFHNVoGF3BRhBQts_SwCWIH2hkZk2oUJTA
